"""initial schema

Revision ID: 4605ae948edf
Revises: 
Create Date: 2026-06-02 10:12:54.256044
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4605ae948edf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogrulama_kodu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('kod', sa.String(length=10), nullable=False),
    sa.Column('son_gecerlilik', sa.DateTime(), nullable=False),
    sa.Column('kullanildi', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dogrulama_kodu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dogrulama_kodu_email'), ['email'], unique=False)

    op.create_table('gun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gun_date'), ['date'], unique=True)

    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('email_dogrulandi', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kullanici_email'), ['email'], unique=True)

    op.create_table('gun_hipodrom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gun_id', sa.Integer(), nullable=False),
    sa.Column('hipodrom', sa.String(length=40), nullable=False),
    sa.Column('birim', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['gun_id'], ['gun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gun_id', 'hipodrom')
    )
    with op.batch_alter_table('gun_hipodrom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gun_hipodrom_gun_id'), ['gun_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gun_hipodrom_hipodrom'), ['hipodrom'], unique=False)

    op.create_table('uyelik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('baslangic', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('bitis', sa.DateTime(), nullable=True),
    sa.Column('kaynak', sa.String(length=20), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanici.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uyelik', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uyelik_kullanici_id'), ['kullanici_id'], unique=False)

    op.create_table('altili',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gh_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('legs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['gh_id'], ['gun_hipodrom.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gh_id', 'idx')
    )
    with op.batch_alter_table('altili', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_altili_gh_id'), ['gh_id'], unique=False)

    op.create_table('kosu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gh_id', sa.Integer(), nullable=False),
    sa.Column('kno', sa.Integer(), nullable=False),
    sa.Column('pist', sa.String(length=20), nullable=False),
    sa.Column('mesafe', sa.String(length=20), nullable=False),
    sa.Column('saat', sa.String(length=10), nullable=False),
    sa.Column('n_at', sa.Integer(), nullable=True),
    sa.Column('race_type', sa.String(length=30), nullable=False),
    sa.Column('race_subtype', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['gh_id'], ['gun_hipodrom.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gh_id', 'kno')
    )
    with op.batch_alter_table('kosu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kosu_gh_id'), ['gh_id'], unique=False)

    op.create_table('altili_kademe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('altili_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('ad', sa.String(length=40), nullable=False),
    sa.Column('bedel', sa.Float(), nullable=False),
    sa.Column('komb', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['altili_id'], ['altili.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('altili_kademe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_altili_kademe_altili_id'), ['altili_id'], unique=False)

    op.create_table('altili_sonuc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('altili_id', sa.Integer(), nullable=False),
    sa.Column('winners', sa.JSON(), nullable=False),
    sa.Column('ikramiye', sa.Float(), nullable=True),
    sa.Column('tier_hits', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['altili_id'], ['altili.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('altili_id')
    )
    op.create_table('kosu_bes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kosu_id', sa.Integer(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=4), nullable=False),
    sa.Column('at_no', sa.Integer(), nullable=False),
    sa.Column('at', sa.String(length=60), nullable=False),
    sa.Column('ana', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['kosu_id'], ['kosu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kosu_bes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kosu_bes_kosu_id'), ['kosu_id'], unique=False)

    op.create_table('kosu_sonuc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kosu_id', sa.Integer(), nullable=False),
    sa.Column('kazanan', sa.Integer(), nullable=True),
    sa.Column('ganyan', sa.Float(), nullable=True),
    sa.Column('bes_hit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['kosu_id'], ['kosu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kosu_id')
    )
    op.create_table('altili_ayak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kademe_id', sa.Integer(), nullable=False),
    sa.Column('kno', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('banko_lider', sa.Boolean(), nullable=False),
    sa.Column('secilen', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['kademe_id'], ['altili_kademe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('altili_ayak', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_altili_ayak_kademe_id'), ['kademe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('altili_ayak', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_altili_ayak_kademe_id'))

    op.drop_table('altili_ayak')
    op.drop_table('kosu_sonuc')
    with op.batch_alter_table('kosu_bes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kosu_bes_kosu_id'))

    op.drop_table('kosu_bes')
    op.drop_table('altili_sonuc')
    with op.batch_alter_table('altili_kademe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_altili_kademe_altili_id'))

    op.drop_table('altili_kademe')
    with op.batch_alter_table('kosu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kosu_gh_id'))

    op.drop_table('kosu')
    with op.batch_alter_table('altili', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_altili_gh_id'))

    op.drop_table('altili')
    with op.batch_alter_table('uyelik', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uyelik_kullanici_id'))

    op.drop_table('uyelik')
    with op.batch_alter_table('gun_hipodrom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gun_hipodrom_hipodrom'))
        batch_op.drop_index(batch_op.f('ix_gun_hipodrom_gun_id'))

    op.drop_table('gun_hipodrom')
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kullanici_email'))

    op.drop_table('kullanici')
    with op.batch_alter_table('gun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gun_date'))

    op.drop_table('gun')
    with op.batch_alter_table('dogrulama_kodu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dogrulama_kodu_email'))

    op.drop_table('dogrulama_kodu')
    # ### end Alembic commands ###
